name: bybit-ai-trading-pipeline
services:
- name: ai-pipeline-api
  source_dir: /
  github:
    repo: Zvxndr/Bybit-bot
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile
  buildpack_stack: container
  run_command: "python main.py"
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8000
  health_check:
    http_path: /health
    failure_threshold: 15
    success_threshold: 2
  envs:
  - key: ENVIRONMENT
    value: production
  - key: PORT
    value: "8000"
  - key: PYTHONPATH
    value: /app
  - key: PYTHONUNBUFFERED
    value: "1"
  # Add your Bybit API credentials here for real trading
  # - key: BYBIT_API_KEY
  #   value: your_testnet_api_key
  # - key: BYBIT_SECRET
  #   value: your_testnet_secret_key