debug_mode: true
debug_settings:
  disable_real_trading: true
  disable_api_orders: true
  disable_position_changes: true
  force_testnet: true
  mock_api_responses: true
  api_call_logging: true
  use_historical_data: true
  historical_data_source: src/data/speed_demon_cache/market_data.db
  fallback_to_mock: true
  show_debug_warnings: true
  enable_debug_panel: true
  log_ui_interactions: true
  use_mock_balances: false
  preserve_real_data: true
  max_debug_runtime: 3600
  auto_shutdown_on_error: true
phase:
  current: HISTORICAL_DATA_DEBUGGING
  trading_allowed: false
  data_source: historical
  description: Using real historical market data for realistic debugging
logging:
  level: DEBUG
  console_output: true
  file_output: true
  debug_log_file: logs/debug_session.log
historical_data:
  enabled: true
  database_path: src/data/speed_demon_cache/market_data.db
  preferred_symbols:
  - BTCUSDT
  - ETHUSDT
  - SOLUSDT
  max_records_per_query: 100
  balance_calculation_method: dynamic
  position_simulation: true
  trade_history_limit: 50
  database_populated: true
  data_quality_score: 0.98386
  last_updated: '2025-09-28T13:24:27.178266'
  deployment_ready: true
mock_data:
  testnet_balance: 10000.0
  mainnet_balance: 0.0
  paper_balance: 100000.0
  mock_positions:
  - symbol: BTCUSDT
    side: long
    size: '0.001'
    entry_price: '67500.00'
    pnl: '+15.50'
  mock_trades:
  - symbol: BTCUSDT
    side: buy
    size: '0.001'
    price: '67500.00'
    timestamp: '2024-01-20 14:30:00'
    pnl: '+15.50'
