debug_mode: false  # PRODUCTION MODE - Live trading enabled
# Production configuration - Live trading with comprehensive logging
auto_run_debug_tests: false  # DISABLED - Production mode
run_data_wipe_tests: false   # DISABLED - Protect live data
run_button_tests: false      # DISABLED - Production mode
emergency_stop_on_startup: false  # DISABLED - Production startup

debug_settings:
  disable_real_trading: false      # ENABLED - Live trading allowed
  disable_api_orders: false        # ENABLED - API orders allowed
  disable_position_changes: false  # ENABLED - Position changes allowed
  force_testnet: false             # DISABLED - Allow live trading
  mock_api_responses: false        # DISABLED - Use real API responses
  api_call_logging: true           # ENABLED - Keep comprehensive API logging
  use_historical_data: false       # DISABLED - Use live data
  historical_data_source: src/data/speed_demon_cache/market_data.db
  fallback_to_mock: false          # DISABLED - No mock fallback in production
  show_debug_warnings: false       # DISABLED - Production mode
  enable_debug_panel: false        # DISABLED - Production mode
  log_ui_interactions: true        # ENABLED - Keep UI logging for monitoring
  use_mock_balances: false         # DISABLED - Use real balances
  preserve_real_data: true         # ENABLED - Protect live data
  max_debug_runtime: 86400         # 24 hours - Extended for production
  auto_shutdown_on_error: true     # ENABLED - Safety measure
phase:
  current: PRODUCTION_LIVE_TRADING
  trading_allowed: true
  data_source: live
  description: Production mode with live trading and comprehensive logging
logging:
  level: INFO                      # Production logging level (comprehensive but not debug)
  console_output: true             # ENABLED - Keep console output
  file_output: true               # ENABLED - Keep comprehensive file logging
  debug_log_file: logs/production_session.log  # Production log file
historical_data:
  enabled: false                   # DISABLED - Use live data in production
  database_path: src/data/speed_demon_cache/market_data.db
  preferred_symbols:
  - BTCUSDT
  - ETHUSDT
  - SOLUSDT
  max_records_per_query: 100
  balance_calculation_method: live  # Use live balance calculation
  position_simulation: false       # DISABLED - Use real positions
  trade_history_limit: 50
  database_populated: true
  data_quality_score: 0.98386
  last_updated: '2025-09-28T13:24:27.178266'
  deployment_ready: true
mock_data:
  testnet_balance: 10000.0
  mainnet_balance: 0.0
  paper_balance: 100000.0
  mock_positions:
  - symbol: BTCUSDT
    side: long
    size: '0.001'
    entry_price: '67500.00'
    pnl: '+15.50'
  mock_trades:
  - symbol: BTCUSDT
    side: buy
    size: '0.001'
    price: '67500.00'
    timestamp: '2024-01-20 14:30:00'
    pnl: '+15.50'
