# DEBUG MODE CONFIGURATION
# =========================
# This file controls debugging behavior during development phase
# Set debug_mode: true to prevent ALL real trading operations

debug_mode: true  # CRITICAL: Prevents all real trading when true

# Debug Settings
debug_settings:
  # Trading Controls
  disable_real_trading: true      # Prevent actual trades
  disable_api_orders: true        # Block order placement API calls
  disable_position_changes: true  # Prevent position modifications
  
  # API Safety
  force_testnet: true            # Force testnet even if mainnet configured
  mock_api_responses: true       # Use mock data instead of real API calls
  api_call_logging: true         # Log all API calls for debugging
  
  # UI Controls
  show_debug_warnings: true      # Display debug mode warnings in UI
  enable_debug_panel: true       # Show debug information panel
  log_ui_interactions: true     # Log all button clicks and UI actions
  
  # Data Management  
  use_mock_balances: true        # Use fake balance data
  preserve_real_data: true       # Don't modify real account data
  
  # Safety Timeouts
  max_debug_runtime: 3600        # Max runtime in debug mode (1 hour)
  auto_shutdown_on_error: true   # Shutdown on critical errors

# Logging Configuration
logging:
  level: DEBUG
  console_output: true
  file_output: true
  debug_log_file: "logs/debug_session.log"
  
# Mock Data for Testing
mock_data:
  testnet_balance: 10000.00
  mainnet_balance: 0.00
  paper_balance: 100000.00
  
  mock_positions:
    - symbol: "BTCUSDT"
      side: "long"
      size: "0.001"
      entry_price: "67500.00"
      pnl: "+15.50"
      
  mock_trades:
    - symbol: "BTCUSDT"
      side: "buy"
      size: "0.001"
      price: "67500.00"
      timestamp: "2024-01-20 14:30:00"
      pnl: "+15.50"

# Debug Phase Indicators
phase:
  current: "PRIVATE_USE_DEBUGGING"
  status: "DEVELOPMENT"
  trading_allowed: false
  live_deployment: false