development:
  debug: true
  fast_testing: true
  mock_trading: true
  mode: local
logging:
  backup_count: 5
  file_rotation: true
  level: INFO
  max_file_size: 10MB
performance:
  cache_data: true
  memory_optimization: true
  parallel_processing: true
