# Bybit API credentials - REPLACE WITH REAL VALUES
bybit:
  api_key: "${BYBIT_TESTNET_API_KEY}"
  api_secret: "${BYBIT_TESTNET_API_SECRET}"
  testnet: true

# Database credentials - REPLACE WITH REAL VALUES
database:
  password: "${DB_PASSWORD}"

# Redis credentials - REPLACE WITH REAL VALUES
redis:
  password: "${REDIS_PASSWORD}"

# API security keys - REPLACE WITH REAL VALUES
api:
  secret_key: "${API_SECRET_KEY}"
  api_keys:
    admin: "${ADMIN_API_KEY}"
    service: "${SERVICE_API_KEY}"

# Security keys - REPLACE WITH REAL VALUES
security:
  encryption_key: "${ENCRYPTION_KEY}"
  password_salt: "${PASSWORD_SALT}"
  jwt_secret_key: "${JWT_SECRET_KEY}"

# Dashboard credentials - REPLACE WITH REAL VALUES
dashboard:
  api_key: "${DASHBOARD_API_KEY}"

# Grafana admin password - REPLACE WITH REAL VALUE
grafana:
  admin_password: "${GRAFANA_ADMIN_PASSWORD}"

# System admin password - REPLACE WITH REAL VALUE
admin:
  password: "${ADMIN_PASSWORD}"