# Bybit API credentials for testing
bybit:
  api_key: "YOUR_BYBIT_API_KEY_HERE"
  api_secret: "YOUR_BYBIT_API_SECRET_HERE"
  testnet: true

# Database credentials
database:
  password: "test-password"

# Redis credentials  
redis:
  password: "test-password"

# API security keys
api:
  secret_key: "test-secret-key"
  api_keys:
    admin: "admin-api-key"
    service: "service-api-key"

# Security keys
security:
  encryption_key: "test-encryption-key"
  password_salt: "test-salt"
  jwt_secret_key: "test-jwt-secret"

# Dashboard credentials
dashboard:
  api_key: "dashboard-api-key"