apiVersion: apps/v1
kind: Deployment
metadata:
  name: bybit-bot
  labels:
    app: bybit-bot
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: bybit-bot
  template:
    metadata:
      labels:
        app: bybit-bot
    spec:
      containers:
      - name: bybit-bot
        image: bybit-bot:latest
        ports:
        - containerPort: 8080
        env:
        - name: ENV
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: bybit-bot-service
spec:
  selector:
    app: bybit-bot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
