# Unified Configuration System - Phase 4 Configuration Consolidation

version: "1.0.0"
environment: development
created_at: "2024-01-01T00:00:00"
updated_at: "2024-01-01T00:00:00"

# ============================================================================
# EXCHANGE CREDENTIALS (by environment)
# ============================================================================
exchange:
  development:
    api_key: ""  # Set via environment variable or CLI
    api_secret: ""  # Set via environment variable or CLI  
    is_testnet: true
    base_url: "https://api-testnet.bybit.com"
    recv_window: 5000
  
  staging:
    api_key: ""
    api_secret: ""
    is_testnet: true
    base_url: "https://api-testnet.bybit.com"
    recv_window: 5000
  
  production:
    api_key: ""
    api_secret: ""
    is_testnet: false
    base_url: "https://api.bybit.com"
    recv_window: 5000

# ============================================================================
# DATABASE CONFIGURATION
# ============================================================================
database:
  dialect: duckdb  # duckdb, postgresql, sqlite
  host: localhost
  port: 5432
  database: trading_bot
  username: trader
  password: ""  # Set via environment variable
  ssl_mode: prefer
  pool_size: 10
  max_overflow: 20
  echo: false

# ============================================================================
# TRADING CONFIGURATION
# ============================================================================
trading:
  mode: conservative  # conservative, aggressive, hybrid
  base_balance: 0.0  # Will be fetched from Bybit API
  
  # Conservative mode configuration
  conservative_mode:
    portfolio_drawdown_limit: 0.15
    strategy_drawdown_limit: 0.10
    sharpe_ratio_min: 0.8
    var_daily_limit: 0.05
    consistency_min: 0.7
    risk_ratio: 0.02
  
  # Aggressive mode configuration
  aggressive_mode:
    portfolio_drawdown_limit: 0.25
    strategy_drawdown_limit: 0.20
    sharpe_ratio_min: 0.5
    var_daily_limit: 0.10
    consistency_min: 0.5
    max_risk_ratio: 0.10
    min_risk_ratio: 0.02
    balance_thresholds:
      low: 5000.0
      medium: 15000.0
      high: 50000.0
    risk_decay: exponential
  
  # Order execution settings
  order_type: limit
  max_slippage: 0.001
  order_timeout: 30
  
  # Trading pairs and timeframes
  symbols:
    - BTCUSDT
    - ETHUSDT
    - ADAUSDT
    - DOTUSDT
  
  timeframes:
    primary: "1h"
    secondary: "4h"
    daily: "1d"

# ============================================================================
# MACHINE LEARNING CONFIGURATION
# ============================================================================
ml:
  # Feature engineering
  lookback_periods: [5, 10, 20, 50, 100]
  
  technical_indicators:
    - sma
    - ema
    - rsi
    - macd
    - bollinger_bands
    - atr
    - stochastic
    - williams_r
    - cci
    - adx
  
  statistical_features:
    - returns
    - log_returns
    - volatility
    - skewness
    - kurtosis
    - autocorrelation
    - variance_ratio
  
  # Model configurations
  models:
    lightgbm:
      n_estimators: 1000
      learning_rate: 0.1
      max_depth: 6
      feature_fraction: 0.8
      bagging_fraction: 0.8
      random_state: 42
      early_stopping_rounds: 100
      verbose: -1
    
    xgboost:
      n_estimators: 1000
      learning_rate: 0.1
      max_depth: 6
      subsample: 0.8
      colsample_bytree: 0.8
      random_state: 42
      early_stopping_rounds: 100
      verbose: 0
    
    catboost:
      iterations: 1000
      learning_rate: 0.1
      depth: 6
      random_state: 42
      early_stopping_rounds: 100
      verbose: false
  
  # Cross-validation settings
  cross_validation:
    n_splits: 5
    test_size: 0.2
    purge_days: 1
    embargo_days: 1
    shuffle: false
    random_state: 42

# ============================================================================
# BACKTESTING CONFIGURATION
# ============================================================================
backtesting:
  # Walk-forward analysis
  walk_forward:
    initial_window: 252  # Trading days (1 year)
    step_size: 21        # Trading days (1 month)
    oos_period: 21       # Out-of-sample period
    min_trades: 30       # Minimum trades for validation
    max_iterations: 50   # Maximum walk-forward iterations
  
  # Validation thresholds by trading mode
  validation:
    conservative:
      min_sharpe: 0.8
      max_drawdown: 0.15
      min_profit_factor: 1.2
      min_win_rate: 0.4
      max_var_95: 0.05
    
    aggressive:
      min_sharpe: 0.5
      max_drawdown: 0.25
      min_profit_factor: 1.1
      min_win_rate: 0.35
      max_var_95: 0.10
    
    hybrid:
      min_sharpe: 0.6
      max_drawdown: 0.20
      min_profit_factor: 1.15
      min_win_rate: 0.38
      max_var_95: 0.08

# ============================================================================
# API AND CONNECTIVITY CONFIGURATION
# ============================================================================
rate_limits:
  market_data: 120      # Requests per second
  trading: 50          # Requests per second
  account: 20          # Requests per second
  websocket: 10        # Connections per second
  enable_rate_limiting: true

connection:
  pool_size: 100
  timeout: 30          # Request timeout in seconds
  max_retries: 3
  keepalive_timeout: 300
  enable_compression: true
  ssl_verify: true

websocket:
  ping_interval: 20    # Seconds
  ping_timeout: 10     # Seconds
  close_timeout: 10    # Seconds
  max_reconnect_attempts: 10
  base_reconnect_delay: 1.0    # Seconds
  max_reconnect_delay: 60.0    # Seconds
  enable_compression: true
  message_queue_size: 1000

cache:
  backend: memory      # memory, redis, hybrid
  enable_caching: true
  cache_size: 10000
  cache_ttl_seconds: 60
  cleanup_interval: 300
  
  # Redis configuration (if using Redis backend)
  redis_host: localhost
  redis_port: 6379
  redis_db: 0
  redis_password: ""   # Set via environment variable

# ============================================================================
# AUSTRALIAN COMPLIANCE CONFIGURATION
# ============================================================================
australian_compliance:
  timezone: "Australia/Sydney"
  tax_year: "2024"
  enable_tax_reporting: true
  cgt_threshold: 12000.0    # CGT threshold in AUD
  record_all_trades: true
  export_format: csv        # csv, json, xlsx
  reporting_currency: AUD

# ============================================================================
# LOGGING CONFIGURATION
# ============================================================================
logging:
  level: INFO           # DEBUG, INFO, WARNING, ERROR, CRITICAL
  enable_file_logging: true
  log_file_path: "logs/trading_bot.log"
  max_file_size_mb: 100
  backup_count: 5
  enable_console_logging: true
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# ============================================================================
# SECURITY CONFIGURATION
# ============================================================================
security:
  enable_encryption: true
  secret_key: ""        # Set via environment variable or auto-generated
  enable_api_key_rotation: false
  key_rotation_interval_hours: 24
  enable_ip_whitelist: false
  allowed_ips: []
  min_tls_version: "1.2"

# ============================================================================
# MONITORING AND ALERTING
# ============================================================================
monitoring:
  enable_health_checks: true
  health_check_interval: 60    # Seconds
  enable_metrics: true
  metrics_port: 9090
  enable_alerts: true
  
  # Email alerting configuration
  smtp_server: ""              # Set via environment variable
  smtp_port: 587
  email_username: ""           # Set via environment variable
  email_password: ""           # Set via environment variable
  alert_email: ""              # Set via environment variable

# ============================================================================
# API SERVER CONFIGURATION
# ============================================================================
api:
  host: "0.0.0.0"
  port: 8000
  workers: 1
  enable_auth: true
  enable_docs: false           # Disable in production
  enable_metrics: true
  cors_origins: []
  rate_limit_requests: 100     # Per minute

# ============================================================================
# FEATURE FLAGS
# ============================================================================
enable_trading: false          # IMPORTANT: Set to true only when ready
enable_websockets: true
enable_market_data: true
enable_risk_management: true
enable_ml_integration: true
enable_backtesting: true

# ============================================================================
# CUSTOM SETTINGS
# ============================================================================
custom_settings:
  # Add any custom configuration here
  experimental_features:
    enable_advanced_orders: false
    enable_portfolio_optimization: false
    enable_sentiment_analysis: false
  
  # Development/testing settings
  development:
    enable_debug_mode: true
    mock_api_responses: false
    save_raw_data: true
    detailed_logging: true